<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{b807fc2e-1114-4564-88f5-927cd81451cd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbTransport: TransportSystem('MAIN.TPS_A');
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbTransport();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>