<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{fd9c62c6-08ad-42ca-a926-6612bb53b12d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbSuperBohrmachine: SuperBohrmachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbSuperBohrmachine();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>