<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{4ef65e4f-3fc3-4b8d-9082-32ff912527e7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bWerkStueckLiegtAn AT %Q*: BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>