<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{320df1f8-468e-46a8-b990-e02f16a957b9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR	
	fbTransportSlave: TransportSystemSlave('MAIN.TPS_B');
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbTransportSlave();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="13" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="21" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>