<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{320df1f8-468e-46a8-b990-e02f16a957b9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbTransportSlave: TransportSystemSlave('MAIN.TPS_B');
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbTransportSlave();]]></ST>
    </Implementation>
    <Method Name="Setup" Id="{c8327a17-9761-42a4-adab-c913765a3e46}">
      <Declaration><![CDATA[{attribute 'call_after_init'}
METHOD Setup : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="MAIN">
      <LineId Id="15" Count="0" />
    </LineIds>
    <LineIds Name="MAIN.Setup">
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>