<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="Sensor" Id="{94111f90-a3c6-4dbb-a062-393355ac9c90}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bWerkStueckLiegtAn AT %Q*: BOOL := FALSE;
	
	// Werkstücksimulation. Random-Timer.
	fbRandom: DRAND;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
Simulation:
p = Position wenn das Werkstück zum Bohren anliegt
l = Länge Werkstück
Werkstück wurde abtransportiert: actPos = p + l
Wenn abtransportiert: Timer (je nachdem wie schnell das Bohren ist, Random 5-7s)
(Bohren dauert aktuell ~40s... schneller machen...)

*)]]></ST>
    </Implementation>
    <LineIds Name="Sensor">
      <LineId Id="14" Count="6" />
      <LineId Id="23" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>