///////////////////////////////////////////////////////////////////////////////
// ControllerServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Controller = 0x3F000000;
#define SRVNAME_CONTROLLER "Controller"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ControllerCModuleController = {0xa1d3d973,0x539c,0x4d63,{0x8c,0xce,0x4d,0x66,0x9f,0x9f,0xdd,0x95}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleControllerBohrmaschine = 0x00000002;
const PTCID PID_ModuleControllerTransportMaster = 0x00000003;
const PTCID PID_ModuleControllerTransportSlave = 0x00000004;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#pragma pack(push,1)
typedef struct _ModuleControllerInputs
{
	bool WerkstueckLiegtAn;
	OTCID oidBohrmaschine;
	OTCID oidTransportA;
	OTCID oidTransportB;
} ModuleControllerInputs, *PModuleControllerInputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleControllerInputs 0
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_2FF1D4E0_EFA3_45BB_B4FD_1AB5D871BEED_INCLUDED_)
#define _TC_IID_2FF1D4E0_EFA3_45BB_B4FD_1AB5D871BEED_INCLUDED_
TCOM_DECL_INTERFACE("2ff1d4e0-efa3-45bb-b4fd-1ab5d871beed", I_Bohrmaschine)
#endif // !defined(_TC_IID_2FF1D4E0_EFA3_45BB_B4FD_1AB5D871BEED_INCLUDED_)

#if !defined(_TC_IID_483A31B0_2301_45A5_BDA0_4390BE118005_INCLUDED_)
#define _TC_IID_483A31B0_2301_45A5_BDA0_4390BE118005_INCLUDED_
TCOM_DECL_INTERFACE("483a31b0-2301-45a5-bda0-4390be118005", I_Transport)
#endif // !defined(_TC_IID_483A31B0_2301_45A5_BDA0_4390BE118005_INCLUDED_)

#if !defined(_TC_IID_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)
#define _TC_IID_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_
TCOM_DECL_INTERFACE("8fb536d1-f7ee-4acc-a46d-fd4c09c81841", I_TransportSlave)
#endif // !defined(_TC_IID_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
