///////////////////////////////////////////////////////////////////////////////
// ControllerServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Controller = 0x3F000000;
#define SRVNAME_CONTROLLER "Controller"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ControllerCModuleController = {0xa1d3d973,0x539c,0x4d63,{0x8c,0xce,0x4d,0x66,0x9f,0x9f,0xdd,0x95}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleControllerBohrmaschine = 0x00000002;
const PTCID PID_ModuleControllerTransportMaster = 0x00000003;
const PTCID PID_ModuleControllerTransportSlave = 0x00000004;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_B37DCF0F_032A_48DA_9E72_FE38F64AE081_INCLUDED_)
#define _TC_TYPE_B37DCF0F_032A_48DA_9E72_FE38F64AE081_INCLUDED_
enum Zustand : unsigned char {
	starting = 0,
	started = 1,
	stopping = 2,
	stopped = 3
};
#endif // !defined(_TC_TYPE_B37DCF0F_032A_48DA_9E72_FE38F64AE081_INCLUDED_)

#if !defined(_TC_TYPE_FA9D66EE_0236_4C7E_B7EA_32284FDD303F_INCLUDED_)
#define _TC_TYPE_FA9D66EE_0236_4C7E_B7EA_32284FDD303F_INCLUDED_
BEGIN_SCOPED_TYPED_ENUM(E_STATES_TRANSPORT_A, unsigned char)
 {
	STARTING = 0,
	STARTED = 1,
	STOPPING = 2,
	STOPPED = 3
};
END_SCOPED_TYPED_ENUM(E_STATES_TRANSPORT_A, unsigned char)
#endif // !defined(_TC_TYPE_FA9D66EE_0236_4C7E_B7EA_32284FDD303F_INCLUDED_)

#if !defined(_TC_TYPE_16FD3C19_537A_42F0_B109_DF6DADA71F81_INCLUDED_)
#define _TC_TYPE_16FD3C19_537A_42F0_B109_DF6DADA71F81_INCLUDED_
BEGIN_SCOPED_TYPED_ENUM(E_STATES_TRANSPORT_B, unsigned char)
 {
	ESYNCING = 0,
	ESYNCED = 1,
	EHALTING = 2,
	EHALTED = 3
};
END_SCOPED_TYPED_ENUM(E_STATES_TRANSPORT_B, unsigned char)
#endif // !defined(_TC_TYPE_16FD3C19_537A_42F0_B109_DF6DADA71F81_INCLUDED_)

#if !defined(_TC_TYPE_547E8604_F2E5_484E_8D8A_3992CB2003F8_INCLUDED_)
#define _TC_TYPE_547E8604_F2E5_484E_8D8A_3992CB2003F8_INCLUDED_
typedef struct _ST_Config
{
	double rLaenge;
	double rBreite;
	double rDicke;
} ST_Config, *PST_Config;
#endif // !defined(_TC_TYPE_547E8604_F2E5_484E_8D8A_3992CB2003F8_INCLUDED_)

#if !defined(_TC_TYPE_3F18BD17_0195_49DE_AFF3_02A3826473C7_INCLUDED_)
#define _TC_TYPE_3F18BD17_0195_49DE_AFF3_02A3826473C7_INCLUDED_
BEGIN_SCOPED_TYPED_ENUM(E_STATES_BOHRMACHINE, unsigned char)
 {
	EWAITING = 0,
	EMOVING = 1,
	EDRILLING = 2,
	ESTOPPING = 3,
	ESTOPPED = 4
};
END_SCOPED_TYPED_ENUM(E_STATES_BOHRMACHINE, unsigned char)
#endif // !defined(_TC_TYPE_3F18BD17_0195_49DE_AFF3_02A3826473C7_INCLUDED_)

#if !defined(_TC_TYPE_B008CE37_8A01_489B_89E4_5BDAC7669296_INCLUDED_)
#define _TC_TYPE_B008CE37_8A01_489B_89E4_5BDAC7669296_INCLUDED_
enum E_OpStates : unsigned char {
	Stopping = 0,
	Syncing = 1,
	Drilling = 2,
	Synced = 3
};
#endif // !defined(_TC_TYPE_B008CE37_8A01_489B_89E4_5BDAC7669296_INCLUDED_)

typedef struct _ModuleControllerInputIPointers
{
	OTCID oidBohrmaschine;
	OTCID oidTransportA;
	OTCID oidTransportB;
} ModuleControllerInputIPointers, *PModuleControllerInputIPointers;

typedef struct _ModuleControllerUIControls
{
	bool Start;
	bool Stop;
	bool BtnStartEnabled;
	bool BtnStopEnabled;
} ModuleControllerUIControls, *PModuleControllerUIControls;

#pragma pack(push,1)
typedef struct _ModuleControllerState
{
	Zustand eZustand;
	ST_Config Config;
	E_OpStates eOpZustand;
} ModuleControllerState, *PModuleControllerState;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleControllerTransportA
{
	E_STATES_TRANSPORT_A State;
} ModuleControllerTransportA, *PModuleControllerTransportA;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleControllerBohrmaschine
{
	E_STATES_BOHRMACHINE State;
} ModuleControllerBohrmaschine, *PModuleControllerBohrmaschine;
#pragma pack(pop)

typedef struct _ModuleControllerTransportB
{
	E_STATES_TRANSPORT_B State;
	bool WerkstueckLiegtAn;
} ModuleControllerTransportB, *PModuleControllerTransportB;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleControllerInputIPointers 0
#define ADI_ModuleControllerUIControls 2
#define ADI_ModuleControllerState 3
#define ADI_ModuleControllerTransportA 4
#define ADI_ModuleControllerBohrmaschine 6
#define ADI_ModuleControllerTransportB 7
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_EB8E918B_9ED3_43F0_B318_89D13AAE5FBF_INCLUDED_)
#define _TC_IID_EB8E918B_9ED3_43F0_B318_89D13AAE5FBF_INCLUDED_
TCOM_DECL_INTERFACE("eb8e918b-9ed3-43f0-b318-89d13aae5fbf", I_Transport)
#endif // !defined(_TC_IID_EB8E918B_9ED3_43F0_B318_89D13AAE5FBF_INCLUDED_)

#if !defined(_TC_IID_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)
#define _TC_IID_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_
TCOM_DECL_INTERFACE("8fb536d1-f7ee-4acc-a46d-fd4c09c81841", I_TransportSlave)
#endif // !defined(_TC_IID_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)

#if !defined(_TC_IID_9B44EC8E_A52C_41E6_9085_68FADB7DFEB4_INCLUDED_)
#define _TC_IID_9B44EC8E_A52C_41E6_9085_68FADB7DFEB4_INCLUDED_
TCOM_DECL_INTERFACE("9b44ec8e-a52c-41e6-9085-68fadb7dfeb4", I_Bohrmaschine)
#endif // !defined(_TC_IID_9B44EC8E_A52C_41E6_9085_68FADB7DFEB4_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
