///////////////////////////////////////////////////////////////////////////////
// ControllerInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ControllerServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_2FF1D4E0_EFA3_45BB_B4FD_1AB5D871BEED_INCLUDED_)
#define _TC_TYPE_2FF1D4E0_EFA3_45BB_B4FD_1AB5D871BEED_INCLUDED_
struct __declspec(novtable) I_Bohrmaschine : public ITcUnknown
{
	virtual HRESULT TCOMAPI Start()=0;
	virtual HRESULT TCOMAPI Stop()=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_Bohrmaschine, IID_I_Bohrmaschine);
#endif // !defined(_TC_TYPE_2FF1D4E0_EFA3_45BB_B4FD_1AB5D871BEED_INCLUDED_)

#if !defined(_TC_TYPE_483A31B0_2301_45A5_BDA0_4390BE118005_INCLUDED_)
#define _TC_TYPE_483A31B0_2301_45A5_BDA0_4390BE118005_INCLUDED_
struct __declspec(novtable) I_Transport : public ITcUnknown
{
	virtual HRESULT TCOMAPI Start()=0;
	virtual HRESULT TCOMAPI Stop()=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_Transport, IID_I_Transport);
#endif // !defined(_TC_TYPE_483A31B0_2301_45A5_BDA0_4390BE118005_INCLUDED_)

#if !defined(_TC_TYPE_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)
#define _TC_TYPE_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_
struct __declspec(novtable) I_TransportSlave : public ITcUnknown
{
	virtual HRESULT TCOMAPI Halt()=0;
	virtual HRESULT TCOMAPI SyncWithMaster()=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_TransportSlave, IID_I_TransportSlave);
#endif // !defined(_TC_TYPE_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)

///</AutoGeneratedContent>
