///////////////////////////////////////////////////////////////////////////////
// ControllerInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ControllerServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_EB8E918B_9ED3_43F0_B318_89D13AAE5FBF_INCLUDED_)
#define _TC_TYPE_EB8E918B_9ED3_43F0_B318_89D13AAE5FBF_INCLUDED_
struct __declspec(novtable) I_Transport : public ITcUnknown
{
	virtual HRESULT TCOMAPI Start(double rVelocity)=0;
	virtual HRESULT TCOMAPI Stop()=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_Transport, IID_I_Transport);
#endif // !defined(_TC_TYPE_EB8E918B_9ED3_43F0_B318_89D13AAE5FBF_INCLUDED_)

#if !defined(_TC_TYPE_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)
#define _TC_TYPE_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_
struct __declspec(novtable) I_TransportSlave : public ITcUnknown
{
	virtual HRESULT TCOMAPI Halt()=0;
	virtual HRESULT TCOMAPI SyncWithMaster()=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_TransportSlave, IID_I_TransportSlave);
#endif // !defined(_TC_TYPE_8FB536D1_F7EE_4ACC_A46D_FD4C09C81841_INCLUDED_)

#if !defined(_TC_TYPE_9B44EC8E_A52C_41E6_9085_68FADB7DFEB4_INCLUDED_)
#define _TC_TYPE_9B44EC8E_A52C_41E6_9085_68FADB7DFEB4_INCLUDED_
struct __declspec(novtable) I_Bohrmaschine : public ITcUnknown
{
	virtual HRESULT TCOMAPI Start(ST_Config& config)=0;
	virtual HRESULT TCOMAPI Stop()=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_Bohrmaschine, IID_I_Bohrmaschine);
#endif // !defined(_TC_TYPE_9B44EC8E_A52C_41E6_9085_68FADB7DFEB4_INCLUDED_)

///</AutoGeneratedContent>
